name: trimsock.gd CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths: ["trimsock.gd/**/*"]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        godot-version: [4.2.2, 4.3.0, 4.4.0, 4.5.0]
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: ${{ matrix.godot-version }}
          use-dotnet: false
          include-templates: false
      - name: Verify setup
        run: godot --version
      - name: Run tests
        run: cd trimsock.gd && sh/test.sh
  check-uids:
    name: Check UIDs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.5.0
          use-dotnet: false
          include-templates: false
      - name: Verify setup
        run: godot --version
      - name: Check UIDs
        run: cd trimsock.gd && sh/check-uids.sh
  
